[run]
sample = 'testpcen08'
ncores = 32
overwrite = true
plot = false

[catalog]
lenses = '../cats/DESY3/desy3_redmapper_cluster-ws.fits'
sources = '../cats/DESY3/desy3_metacal-unsheared-zbins_w-pix128_25314.fits'
angles = '../'

[profile]
nbins = 15
rin = 0.2 #mpc/h
rout = 5.0 #mpc/h
njk = 40
binning = 'log' # 'lin'

[lensescut]
# redshift bin edges
zedges = [0.1, 0.34, 0.47, 0.58]
# richness lambda bin edges
ledges = [20, 30, 45, 60, 250]
# probability cut (grather than) for good centre
pcen = 0.8

